<a href="https://colab.research.google.com/github/dfirm/iads_day10/blob/main/Twitter_SentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install Tweepy
!pip install tweepy

In [2]:
import re
import tweepy
from tweepy import OAuthHandler
consumer_api_key = ''
consumer_api_secret = ''
access_token = ''
access_token_secret = ''

In [3]:
authorizer = OAuthHandler(consumer_api_key, consumer_api_secret)
authorizer.set_access_token(access_token, access_token_secret)

In [4]:
api = tweepy.API(authorizer ,timeout=15)
all_tweets = []
search_query = 'SUFFOLK'

for tweet_object in tweepy.Cursor(api.search,q=search_query+" -filter:retweets",lang='en',result_type='recent').items(200):
    all_tweets.append(tweet_object.text)
    print(tweet_object.text)

Great to chat to @MarkGlennMurphy &amp; people from across Suffolk this morning on BBC Suffolk. A wide ranging discussi… https://t.co/8fmwsa1qcP
DT Jo Churchill MP: Great to chat to Mark Murphy &amp;amp; people from across Suffolk this morning on the BBC Suffolk.… https://t.co/sgkVslI0Eq
@NM_Mum Oh that’s a shame! Fingers crossed the weather is better than forecast for you. We’ve done a few Suffolk an… https://t.co/DKrEY2zz7S
"Theatre on the Coast - Monkey Business Circus", Southwold Common, Suffolk on Fri 6 Aug 2021 4.00PM, tickets: https://t.co/UDP0UnW9Lv
"Theatre on the Coast - Monkey Business Circus", Southwold Common, Suffolk on Fri 6 Aug 2021 12.00PM, tickets: https://t.co/EPzbOMNLBX
@theworldofnat Morning from Suffolk. No adjective required. It’s Suffolk. Enough said.
Gorgeous wood mice babies at #BrickmakersWood 

#Smallwood #CommunityWood #Urbanwood #Ipswich #Suffolk 
#wildlife… https://t.co/1uWVKPAIEP
SUFFOLK: Special Weather Statement issued August 06 at 4:28AM EDT by NWS ht

In [5]:
import numpy as np 
import pandas as pd 
import re  
import nltk # an amazing library to play with natural language
nltk.download('stopwords')  
from nltk.corpus import stopwords 


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [6]:
tweets = pd.read_csv("https://raw.githubusercontent.com/kolaveridi/kaggle-Twitter-US-Airline-Sentiment-/master/Tweets.csv")
print(tweets)

                 tweet_id  ...               user_timezone
0      570306133677760513  ...  Eastern Time (US & Canada)
1      570301130888122368  ...  Pacific Time (US & Canada)
2      570301083672813571  ...  Central Time (US & Canada)
3      570301031407624196  ...  Pacific Time (US & Canada)
4      570300817074462722  ...  Pacific Time (US & Canada)
...                   ...  ...                         ...
14635  569587686496825344  ...                         NaN
14636  569587371693355008  ...                         NaN
14637  569587242672398336  ...                         NaN
14638  569587188687634433  ...  Eastern Time (US & Canada)
14639  569587140490866689  ...                         NaN

[14640 rows x 15 columns]


In [7]:
X = tweets.iloc[:, 10].values  
y = tweets.iloc[:, 1].values

print(X)

['@VirginAmerica What @dhepburn said.'
 "@VirginAmerica plus you've added commercials to the experience... tacky."
 "@VirginAmerica I didn't today... Must mean I need to take another trip!"
 ... '@AmericanAir Please bring American Airlines to #BlackBerry10'
 "@AmericanAir you have my money, you change my flight, and don't answer your phones! Any other suggestions so I can make my commitment??"
 '@AmericanAir we have 8 ppl so we need 2 know how many seats are on the next flight. Plz put us on standby for 4 people on the next flight?']


In [8]:
processed_tweets = []
 
for tweet in range(0, len(X)):  
    # Remove all the special characters
    processed_tweet = re.sub(r'\W', ' ', str(X[tweet]))
 
    # remove all single characters
    processed_tweet = re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_tweet)
 
    # Remove single characters from the start
    processed_tweet = re.sub(r'\^[a-zA-Z]\s+', ' ', processed_tweet) 
 
    # Substituting multiple spaces with single space
    processed_tweet= re.sub(r'\s+', ' ', processed_tweet, flags=re.I)
 
    # Removing prefixed 'b'
    processed_tweet = re.sub(r'^b\s+', '', processed_tweet)
 
    # Converting to Lowercase
    processed_tweet = processed_tweet.lower()
 
    processed_tweets.append(processed_tweet)

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer  
tfidfconverter = TfidfVectorizer(max_features=2000, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))  
X = tfidfconverter.fit_transform(processed_tweets).toarray()


### Task
**The below code is showing how to classify the tweet using Random Forest Classifer. Can you please now create a LSTM model and do the same job as we did during the lab?**

In [10]:
from sklearn.ensemble import RandomForestClassifier
text_classifier = RandomForestClassifier(n_estimators=100, random_state=0)  
text_classifier.fit(X, y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [11]:
for tweet in all_tweets:
    # Remove all the special characters
    processed_tweet = re.sub(r'\W', ' ', tweet)
 
    # remove all single characters
    processed_tweet = re.sub(r'\s+[a-zA-Z]\s+', ' ', processed_tweet)
 
    # Remove single characters from the start
    processed_tweet = re.sub(r'\^[a-zA-Z]\s+', ' ', processed_tweet) 
 
    # Substituting multiple spaces with single space
    processed_tweet= re.sub(r'\s+', ' ', processed_tweet, flags=re.I)
 
    # Removing prefixed 'b'
    processed_tweet = re.sub(r'^b\s+', '', processed_tweet)
 
    # Converting to Lowercase
    processed_tweet = processed_tweet.lower()
 
    sentiment = text_classifier.predict(tfidfconverter.transform([ processed_tweet]).toarray())
    print(processed_tweet ,":", sentiment)


great to chat to markglennmurphy amp people from across suffolk this morning on bbc suffolk wide ranging discussi https co 8fmwsa1qcp : ['positive']
dt jo churchill mp great to chat to mark murphy amp amp people from across suffolk this morning on the bbc suffolk https co sgkvsli0eq : ['positive']
 nm_mum oh that a shame fingers crossed the weather is better than forecast for you we ve done few suffolk an https co dkrey2zz7s : ['negative']
 theatre on the coast monkey business circus southwold common suffolk on fri 6 aug 2021 4 00pm tickets https co udp0unw9lv : ['neutral']
 theatre on the coast monkey business circus southwold common suffolk on fri 6 aug 2021 12 00pm tickets https co epzbomnlbx : ['neutral']
 theworldofnat morning from suffolk no adjective required it suffolk enough said  : ['negative']
gorgeous wood mice babies at brickmakerswood smallwood communitywood urbanwood ipswich suffolk wildlife https co 1uwvkpaiep : ['neutral']
suffolk special weather statement issued augus

In [13]:
import tensorflow as tf
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

data = y
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

encoded = tf.keras.utils.to_categorical(integer_encoded)
print(encoded)
print(X)

['neutral' 'positive' 'neutral' ... 'neutral' 'negative' 'neutral']
[1 2 1 ... 1 0 1]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:

from keras.layers import LSTM
from keras.models import Sequential
from keras.losses import categorical_crossentropy
from keras.layers import Embedding, Dense


max_features = 10000
model = Sequential()
model.add(Embedding(max_features, 32))
model.add(LSTM(32))
model.add(Dense(3, activation='softmax'))
model.compile(optimizer='Adam',
loss='categorical_crossentropy',
metrics=['acc'])

history = model.fit(X, encoded,
                    epochs=10,
                    batch_size=128,
                    validation_split=0.2)



Epoch 1/10
92/92 [==============================] - 30s 96ms/step - loss: 1.0019 - acc: 0.5724 - val_loss: 0.8167 - val_acc: 0.7128
Epoch 2/10
92/92 [==============================] - 8s 90ms/step - loss: 0.9422 - acc: 0.6034 - val_loss: 0.8181 - val_acc: 0.7128
Epoch 3/10
92/92 [==============================] - 8s 91ms/step - loss: 0.9387 - acc: 0.6083 - val_loss: 0.8249 - val_acc: 0.7128
Epoch 4/10
92/92 [==============================] - 8s 87ms/step - loss: 0.9453 - acc: 0.6031 - val_loss: 0.8258 - val_acc: 0.7128
Epoch 5/10
92/92 [==============================] - 8s 85ms/step - loss: 0.9530 - acc: 0.5961 - val_loss: 0.8244 - val_acc: 0.7128
Epoch 6/10
92/92 [==============================] - 8s 85ms/step - loss: 0.9530 - acc: 0.5946 - val_loss: 0.8151 - val_acc: 0.7128
Epoch 7/10
92/92 [==============================] - 8s 85ms/step - loss: 0.9452 - acc: 0.6012 - val_loss: 0.8091 - val_acc: 0.7128
Epoch 8/10
92/92 [==============================] - 8s 86ms/step - loss: 0.9378 - 

In [15]:
(test_loss,train_acc) = model.evaluate(X,encoded)

458/458 [==============================] - 14s 29ms/step - loss: 0.9162 - acc: 0.6269
